export const TYPE = "type";
export const EMAIL = "email";
export const PASSWORD = "password";
export const BUTTON = "button";
export const FIRST_NAME = "First name";
export const LAST_NAME = "Last name";
export const USERNAME = "Username";
export const EMAIL_LABEL = "Email";
export const PASSWORD_LABEL = "Password";
